name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
      - july-updates
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Unit Tests for Shop App
        run: |
          python manage.py test shop.tests

  # - name: Run Unit Tests for Shop App
      #   run: |
      #     python manage.py test shop.tests

      #     - name: Deploy to AWS Lightsail
      #     env:
      #       HOST: ${{ secrets.SERVER_HOST }}
      #       USER: ${{ secrets.SERVER_USER }}
      #       SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     run: |
      #       echo "$SSH_KEY" > deploy_key.pem
      #       chmod 600 deploy_key.pem
      #       ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST << 'EOF'
      #       cd ~/Botgenix_Cloud  # Navigate to your project directory
      #       git pull origin main  # Pull latest changes
        
      #       # Activate the virtual environment
      #       source venv/bin/activate  
        
      #       # Install dependencies
      #       pip install -r requirements.txt  
        
      #       # Run Django migrations
      #       python manage.py migrate  
        
      #       # Collect static files
      #       python manage.py collectstatic --noinput  
        
      #       # Restart Gunicorn service
      #       sudo systemctl restart gunicorn  
        
      #       EOF
      #       rm deploy_key.pem
        

